### PR TITLE
Update SECURITY.md

### PR DESCRIPTION
**Pull request by sirdarckcat**

### CODE REVIEW

**Comment by 1Elle1111** [comment]
Hi

**Review by 1Elle1111 — APPROVED** [review]

**Review by gauntface — APPROVED** [review]

**Comment by 1Elle1111** [comment]
Hi

**Comment by 1Elle1111** [comment]
?

**Review by 1Elle1111 — APPROVED** [review]
Hi

**Review by 1Elle1111 — COMMENTED** [review]
Great

**Comment by gifhupp** [comment]
อัปเดต SECURITY.md #49

**Comment by Jarrian1994** [comment]
> _No description provided._

**Review by fampirsafha — COMMENTED** [review]
#49

**Review by mkevre — COMMENTED** [review]
@1. SECURITY.md

**Comment by Zeenat30** [comment]
You stole my API and license wth

**Comment by Balmasexy** [comment]
I didn't stole it I borrowed it

**Comment by Balmasexy** [comment]
am the world invisible individual explorer

**Comment by Taiseer22** [comment]
ماذا ننتظر

**Pull request merged**
